name = "BSplines"
uuid = "8759ff0c-cd99-11e8-1c1c-d94a817e6fcc"
authors = ["Stefanos Carlstr√∂m <stefanos.carlstrom@gmail.com>"]
version = "0.1.0"

[deps]
BandedMatrices = "aae01518-5342-5314-be14-df237901396f"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
